### ISSUE TITLE
Potentially outdated default value for RestrictDriverInstallationToAdministrators

### ISSUE THREAD

**Issue by v-p-b** [scipag/HardeningKitty#27]
Multiple rule lists define the Point and Print driver installation restriction with the default value of 0:

https://github.com/scipag/HardeningKitty/search?q=RestrictDriverInstallationToAdministrators

Meanwhile, according to the [documentation](https://support.microsoft.com/en-us/topic/kb5005652-manage-new-point-and-print-default-driver-installation-behavior-cve-2021-34481-873642bf-2634-49c5-a23b-6d8e9a302872):

"Windows updates released August 10, 2021 and later will, by default, require administrative privilege to install drivers."

I don't know if HardeningKitty can take into account the current update level of the target system. If it can't, maybe the updated default could be reflected in lists used for builds released after the above date?

**Comment by 0x6d69636b** [comment]
HardeningKitty has (for the moment) no feature to use version or patch level information for finding lists. Therefore I decided setting the default value to _NULL_.

I recommend setting this value in any case, and if it is not explicit set this will be a finding. This issue is addressed in the [development repo](https://github.com/0x6d69636b/windows_hardening/commit/704f360897ae1b1c97397eeb98cbcbd65b773f4a) and will be updated here in the next update.
